### ISSUE TITLE
NameError: name 'get_ipython' is not defined

### ISSUE THREAD

**Issue by robmarkcole** [ericmjl/minimal-panel-app#1]
Hi @ericmjl 
I get the error:
```
(minimal-panel) MacBook-Pro:minimal-panel-app robincole$ panel serve minimal-panel.ipynb 
2019-07-24 05:12:54,716 Starting Bokeh server version 1.0.1 (running on Tornado 5.1.1)
2019-07-24 05:12:54,726 Bokeh app running at: http://localhost:5006/minimal-panel
2019-07-24 05:12:54,726 Starting Bokeh server with process id: 95552
2019-07-24 05:14:14,434 Error running application handler <bokeh.application.handlers.notebook.NotebookHandler object at 0x114609908>: name 'get_ipython' is not defined
File "minimal-panel.ipynb", line 36, in <module>:
"metadata": {}, Traceback (most recent call last):
  File "/Users/robincole/anaconda3/lib/python3.6/site-packages/bokeh/application/handlers/code_runner.py", line 180, in run
    exec(self._code, module.__dict__)
  File "/Users/robincole/Documents/Github/minimal-panel-app/minimal-panel.ipynb", line 36, in <module>
    "metadata": {},
NameError: name 'get_ipython' is not defined
```
Any advice? 
Thanks

**Comment by ericmjl** [comment]
Hmmm, can you try installing ipython explicitly? Maybe that’s missing from environment.yml? If that works, please loop back so I can add it to both environment.yml and requirements.txt - or if you know how to PR, please do so!
